### ISSUE TITLE
mimemagic 0.3.4 not available

### ISSUE THREAD

**Issue by koogled** [ACloudGuru-Resources/Course_Practical_Guide_EKS#19]
When I ran a build I got an error that mimemagic 0.3.4 was unavailable - 

Do you have a quick fix for this, my Ruby is poor to non-existent.

thx

**Comment by mariomerco** [comment]
Hey there, thanks for reporting this!

Given this issue: https://github.com/rails/rails/issues/41750, I've had to be specific on the version of _mimemagic_ required.

I just pushed the change to the repo.

Thanks again!
