### ISSUE TITLE
have issue following helm in Course_Practical_Guide_EKS course

### ISSUE THREAD

**Issue by chrysek70** [ACloudGuru-Resources/Course_Practical_Guide_EKS#20]
krzyss-MacBook-Pro:helm krzys$ pwd
/Users/krzys/SynologyDrive/Course_Practical_Guide_EKS-master/resource-api/infra/helm
krzyss-MacBook-Pro:helm krzys$ helm upgrade --install --namespace development resource-api-development .
Release "resource-api-development" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"
krzyss-MacBook-Pro:helm krzys$ 

krzyss-MacBook-Pro:helm krzys$ helm version --short
v3.6.3+gd506314
krzyss-MacBook-Pro:helm krzys$ kubectl version --short
Client Version: v1.21.3
Server Version: v1.20.4-eks-6b7464
krzyss-MacBook-Pro:helm krzys$

not sure how to bypass this error

**Comment by mariomerco** [comment]
Hi @chrysek70 thanks for showing this! Kubernetes and EKS are updating very quick the versions and the "apps/v1beta2" API version was deprecated back on 1.16. I'll work on this updating all the deployments ASAP. 

Thanks!

**Comment by chrysek70** [comment]
many thanks, you are so awesome.

**Comment by mariomerco** [comment]
Thanks so much for you support! 

I have pushed to the `master` branch a change updating the cluster version to 1.20 (the one you have, and by this time, the latest version EKS support). Also, updated the `apiVersion` to the supported one, **apps/v1**.

**Comment by chrysek70** [comment]
awesome, will try, thank you so much

**Comment by chrysek70** [comment]
awesome, it did work

krzyss-MacBook-Pro:helm krzys$ pwd
/Users/krzys/SynologyDrive/Course_Practical_Guide_EKS-master/resource-api/infra/helm
krzyss-MacBook-Pro:helm krzys$ helm upgrade --install --namespace development resource-api-development .
Release "resource-api-development" does not exist. Installing it now.
NAME: resource-api-development
LAST DEPLOYED: Sun Jul 18 15:51:45 2021
NAMESPACE: development
STATUS: deployed
REVISION: 1
TEST SUITE: None
krzyss-MacBook-Pro:helm krzys$ 

Many thanks for helping fix this problem
