### ISSUE TITLE
front-end container build has COPY failed error

### ISSUE THREAD

**Issue by ansonghua** [ACloudGuru-Resources/Course_Practical_Guide_EKS#23]
I just did clone and docker-compose up and Build On MAC passed. 
But I also tried on both Ubuntu and SUSE got the same error message as below
COPY failed: stat opt/forms/dist: file does not exist
Perhaps npm run build didn't generate files in dist folder? but how come built on MAC worked? 
Can you please help?

**Comment by mariomerco** [comment]
I could t reproduce this on an Ubuntu 21.04 version.
