### ISSUE TITLE
resources-api not starting up in docker-compose

### ISSUE THREAD

**Issue by tomlevlin** [ACloudGuru-Resources/Course_Practical_Guide_EKS#29]
Hi, 

I have tried to start up the site with docker-compose and always hit this same error message regarding the resources-api container:

course_practical_guide_eks-resources-api-1  | [2022-02-20 12:40:03 +0000] [1] [INFO] Starting gunicorn 20.0.0
course_practical_guide_eks-resources-api-1  | [2022-02-20 12:40:03 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
course_practical_guide_eks-resources-api-1  | [2022-02-20 12:40:03 +0000] [1] [INFO] Using worker: sync
course_practical_guide_eks-resources-api-1  | [2022-02-20 12:40:03 +0000] [8] [INFO] Booting worker with pid: 8
course_practical_guide_eks-resources-api-1  | [2022-02-20 12:40:04 +0000] [8] [ERROR] Exception in worker process
course_practical_guide_eks-resources-api-1  | Traceback (most recent call last):
course_practical_guide_eks-resources-api-1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
course_practical_guide_eks-resources-api-1  |     worker.init_process()
course_practical_guide_eks-resources-api-1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 133, in init_process
course_practical_guide_eks-resources-api-1  |     self.load_wsgi()
course_practical_guide_eks-resources-api-1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 142, in load_wsgi
course_practical_guide_eks-resources-api-1  |     self.wsgi = self.app.wsgi()
course_practical_guide_eks-resources-api-1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
course_practical_guide_eks-resources-api-1  |     self.callable = self.load()
course_practical_guide_eks-resources-api-1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
course_practical_guide_eks-resources-api-1  |     return self.load_wsgiapp()
course_practical_guide_eks-resources-api-1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
course_practical_guide_eks-resources-api-1  |     return util.import_app(self.app_uri)
course_practical_guide_eks-resources-api-1  |   File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 331, in import_app
course_practical_guide_eks-resources-api-1  |     mod = importlib.import_module(module)
course_practical_guide_eks-resources-api-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
course_practical_guide_eks-resources-api-1  |     return _bootstrap._gcd_import(name[level:], package, level)
course_practical_guide_eks-resources-api-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
course_practical_guide_eks-resources-api-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
course_practical_guide_eks-resources-api-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
course_practical_guide_eks-resources-api-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
course_practical_guide_eks-resources-api-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
course_practical_guide_eks-resources-api-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
course_practical_guide_eks-resources-api-1  |   File "/wsgi.py", line 1, in <module>
course_practical_guide_eks-resources-api-1  |     from main import app
course_practical_guide_eks-resources-api-1  |   File "/main.py", line 2, in <module>
course_practical_guide_eks-resources-api-1  |     from flask import request
course_practical_guide_eks-resources-api-1  |   File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 19, in <module>
course_practical_guide_eks-resources-api-1  |     from . import json
course_practical_guide_eks-resources-api-1  |   File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 15, in <module>
course_practical_guide_eks-resources-api-1  |     from itsdangerous import json as _json
course_practical_guide_eks-resources-api-1  | ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.10/site-packages/itsdangerous/__init__.py)
course_practical_guide_eks-resources-api-1  | [2022-02-20 12:40:04 +0000] [8] [INFO] Worker exiting (pid: 8)
course_practical_guide_eks-resources-api-1  | [2022-02-20 12:40:04 +0000] [1] [INFO] Shutting down: Master
course_practical_guide_eks-resources-api-1  | [2022-02-20 12:40:04 +0000] [1] [INFO] Reason: Worker failed to boot.
course_practical_guide_eks-resources-api-1 exited with code 3

I have tried this with the following linux distros: Ubuntu 18.04, Ubuntu 20.04 and Amazon Linux 2. Always using the newest versions of docker: 20.10.7 and docker-compose v2.2.3

**Comment by AndreiBanaruTakeda** [comment]
I had to edit [requirements.txt](https://github.com/ACloudGuru-Resources/Course_Practical_Guide_EKS/blob/master/resource-api/src/requirements.txt) and force use of Flask 1.1.4.
More info [here](https://serverfault.com/questions/1094062/error-from-itsdangerous-import-json-as-json-importerror-cannot-import-name-j).

**Comment by tomlevlin** [comment]
Thank you @AndreiBanaruTakeda 

Setting the following lines in the requirements file solved the problem for me:

flask == 1.1.4
markupsafe==2.0.1
