### ISSUE TITLE
Outdated information in Infrastructure/k8s-tooling/1-external-dns/01-initial-external-dns.yaml

### ISSUE THREAD

**Issue by thmsdmmrtn** [ACloudGuru-Resources/Course_Practical_Guide_EKS#36]
Current YAML file does not use latest version of code snippet from repository, fails when applying.

**Comment by mariomerco** [comment]
Hey @thmsdmmrtn thanks for reaching! 

I just updated the code. The `01-initial-external-dns.yaml` file is now deprecated. Please use the `create.sh` file that was recently added.

BTW! right now the course is under a big overhaul updating multiple stuffs and enabling really good features! Stay tuned! great surprises coming soon!
