### ISSUE TITLE
Python Version to Use

### ISSUE THREAD

**Issue by lukewelden** [ACloudGuru-Resources/Course_Practical_Guide_EKS#42]
Hey 👋

For anyone following along in 2024, I ran into some issues regarding python modules not being available in the latest Python 3.12 version specifically `urllib3.packages.six.moves` and `libc`. 

After some playing around and working my way from oldest python docker image to newest python docker image found that `python:3.8-bullseye` got the resources api back up and running. 

I hope this saves someone some time and effore moving forward 😄

**Comment by mariomerco** [comment]
Hey @lukewelden thanks for your contribution! Just as a heads up, this course has been *retired* from  A Cloud Guru and was completely updated. Take a look! https://www.pluralsight.com/cloud-guru/courses/hands-on-with-amazon-eks

**Comment by lukewelden** [comment]
> Hey @lukewelden thanks for your contribution! Just as a heads up, this course has been *retired* from  A Cloud Guru and was completely updated. Take a look! https://www.pluralsight.com/cloud-guru/courses/hands-on-with-amazon-eks

Ah that makes more sense! I've just watched the intro and I can see that the new course makes use of the cloud playgrounds and has setup scripts for each chapter! That's much better, I can't wait to follow along. Thank you @mariomerco
